### PR TITLE
Porting Graphics and Video to C++

### PR DESCRIPTION
**Pull request by wdigger**
The next step in porting to C++

### CODE REVIEW

**Comment by jonls** [comment]
Looks good :+1: There seems to be a regression with the transport info dialog (when double clicking a flag). Instead of being transparent it appears to have garbage in the background. I'm guessing that the surface is not initialized the same way as before.

**Comment by jonls** [comment]
By the way, another regression that I noticed with your last merge which may be related to graphics refactoring: When clicking buttons in the popup dialog the dialog is no longer redrawn. For example, go to options and click on "Music". The music goes away but the checkmark is still there.

**Comment by wdigger** [comment]
I fixed both issues.
But I want to make a few changes before commit.
If you have any suggestions, comments - welcome.

**Comment by wdigger** [comment]
I fixed some possible memory leaks and move version string from window caption to game start dialog.
Version moved basically for fix crash on Mac OS because of asynchronous window creation (as I understand), but I think it's a good step for other systems too.

**Comment by genodeftest** [comment]
This change seems to break compilation for me since make can't find gfx.c for recipe gfx.o. Is this issue known?

**Comment by wdigger** [comment]
@genodeftest in this commit gfx.c replaced with gfx.cc, try to delete all unversioned files and build again.

**Comment by genodeftest** [comment]
Oh, thanks. Running `git clean -dnx`, `git clean -dxf`, `./bootstrap` and `./configure` before `make` fixed this. I just expected a simple `make clean` to work, but it didn't. It might be good to expand `make clean` for this.
Sorry for the noise and thanks again!

**Pull request merged**
