### PR TITLE
Map generator

### PR DESCRIPTION
**Pull request by jonls**
First three commits are some adjustments to the `map_t` interface to allow the map generator functionality to be separated.

Next commit adds an abstract class `MapGenerator` which is responsible for generating a new map. The subclass `ClassicMapGenerator` implements the current map generator from the original game. A further subclass, `ClassicMissionMapGenerator`, provides a convenience for generating maps for missions.

The `map_t` is changed to have the tile data initialized from a `const MapGenerator&`. The initialization works in three steps described in the comment on `map_t`.

### CODE REVIEW

**Comment by wdigger** [comment]
Is it really good idea to change class naming convention?
Which convention we are using now?
Perhaps better to return new map from generator? (map_t *generate<map_generator_t>() or something else?)

**Comment by jonls** [comment]
@wdigger I think using C-style type names in a C++ project is a bit confusing but we can change these all at once if you prefer.

How would you implement `map_t *generate()` on the map generator class? My C++ is a bit rusty so there may be a better way to do this but I'm not sure how the `MapGenerator` would be able to change the internal state of `map_t`. We can make `MapGenerator` a friend of `map_t` but that is not inherited into subclasses of `MapGenerator` as far as I know...?

**Comment by wdigger** [comment]
I was plan to separate map data from operating, mainly for network gaming, but it's the good step for this case too.
Briefly - Replace data (tiles) and setters/getters to separate class (Map) and rename map_t to MapController.
MapGenerator produce Map instance and Game creates MapController with this Map instance.
In this case we have possibility to change internal map data structure independently of operating functionality.
For network purpose I was plan separate tiles for planes (heights, objects, res deposit and so on) and 2-level change cashing - cumulative cache and per-step cache. Per-step cache (map in fact) sends to each remote client (it's a couple of data for concrete plane for one step), cumulative cache (map too) for saving or sending to newly connected client (state = generate(init_random) + com-cache).

**Comment by wdigger** [comment]
Please, wait with changing sometime. I want to change naming whole the project.

**Comment by wdigger** [comment]
Let's merge, I'll fix conflicts on my side.

**Comment by jonls** [comment]
@wdigger This has many conflicts with `map_terrain_t` that I have started to work through earlier. Are you trying to work through the same conflicts?

**Comment by wdigger** [comment]
Yes, but I'm already merge it.

**Pull request merged**
