### PR TITLE
Fix #347: Appveyor: test_save_game excessively time-consuming

### LINKED ISSUE #347: Appveyor: test_save_game excessively time-consuming
The `test_save_game` tests takes up to a minute to run on Appveyor. Here is an example from a recent PR:

```
Running tests...
Test project C:/projects/freeserf
    Start 1: test_map
1/3 Test #1: test_map .........................   Passed    0.19 sec
    Start 2: test_save_game
2/3 Test #2: test_save_game ...................   Passed   58.03 sec
    Start 3: test_map_geometry
3/3 Test #3: test_map_geometry ................   Passed    0.00 sec
100% tests passed, 0 tests failed out of 3
```

On Travis it takes around 2-3 seconds.

### PR DESCRIPTION
**Pull request by wdigger**

### CODE REVIEW

**Comment by wdigger** [comment]
Running tests...
Test project C:/projects/freeserf
    Start 1: test_map
1/3 Test #1: test_map .........................   Passed    0.25 sec
    Start 2: test_save_game
2/3 Test #2: test_save_game ...................   Passed    1.09 sec
    Start 3: test_map_geometry
3/3 Test #3: test_map_geometry ................   Passed    0.02 sec

**Comment by jonls** [comment]
@wdigger I'm curious what the fix was here. Why did this bring down the running time of the test?

**Comment by wdigger** [comment]
@jonls `operator []` devided comma separated string in every call, now values are separate only on load.

**Comment by jonls** [comment]
@wdigger 👍  Thanks.

**Pull request merged**
