### PR TITLE
Switch testing to GTest

### PR DESCRIPTION
**Pull request by wdigger**

### CODE REVIEW

**Comment by wdigger** [comment]
@jonls please merge if you agree

**Comment by jonls** [comment]
- It seems that it is recommended that GTest is included into the project source either by vendoring or as a git submodule (https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project). This would make it easier to setup the build system for freeserf.
- We should use a specific release of GTest (1.8.0). Appveyor and Travis scripts should download this release instead of using the master branch directly.

**Comment by wdigger** [comment]
- ExternalProject it's a very strange feature, on traditional way (now realised) in case of problem we have it on configure stage, we may disable tests building at all or install dependencies and try again. In case of Ext.Proj. problems occurred in build time and have unclear error log ("fail to execute XYZ.sh" or something like that), it's heavy to investigate and fix.

**Comment by wdigger** [comment]
- now we use gtest 1.8.0

**Comment by jonls** [comment]
Great! I'm not sure I understand your comment on ExternalProject. I tried this now but though the configuration (running `cmake`) is successful it indicates that GTest was not found. I was not able to run any of the tests (the `test` target was not generated). I think it would be great if testing would work immediately without having to install dependencies since this is also the recommended setup. Is this not possible? This link seems to have instructions on how to do this: https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project

**Comment by wdigger** [comment]
@jonls just imagine situation when user have no console git tool. It's normal for windows users who don't programming professionally, they use GUI tools.
In this situation building fail with unclear error description and user just close project as unusable.

**Comment by jonls** [comment]
@wdigger Because Git is needed to get the external project? Is it not possible to download the 1.8.0 release from GitHub over HTTP? In any case, you'd need Git to get the Freeserf code so I don't think it is unreasonable to require it.

**Comment by wdigger** [comment]
@jonls do you want to download and build SDL2 and SDL2_mixer the same way? How do these cases differ?

**Comment by wdigger** [comment]
@jonls done. Now gtest downloading and build with cmake.

**Pull request merged**
