### PR TITLE
first release including AI and some core bugfixes

### PR DESCRIPTION
**Pull request by tlongstretch**
Information about how AI works here:
* https://github.com/freeserf/freeserf/wiki/AI---first-release
* https://github.com/freeserf/freeserf/wiki/AI-road-building-logic-and-features

Fork source code here:
* https://github.com/tlongstretch/freeserf-with-AI-plus

Fork compiled binaries here:
* https://github.com/tlongstretch/freeserf-with-AI-plus-binaries

I ran google cpplinter and fixed all issues except whitespace and readability rules I think are counterproductive.

I tried getting appveyor working but it fails building SDL2, I believe because recent vcpkg breaks things that used to work.  If you use vcpkg  2019.11 branch it works.  The newer ones fail.  Not sure how to make appveyor use an old vcpkg.

### CODE REVIEW

**Comment by wdigger** [comment]
You can run cpplint locally ;)
What is you build system? Windows with MSVS?

**Comment by tlongstretch** [comment]
I agree, it is ugly and I was thinking the same thing.  I am looking into how to do this now.  

And yes, I have figured out how to run cmake & nmake check_style locally.   I have two dev machines, one is Windows 7 using Visual Studio 2017 w/Ninja and now NMake, and the other is Linux running VSCode w/ G++

I have gotten the cpplint --filters flags working inside the CppLint.cmake script, and my Appveyor is now building successfully including style checks.

I am going to submit a new Pull request as I have cleaned up a few things since I created this one.

**Comment by tlongstretch** [comment]
I am replacing this pull request with a new one:  https://github.com/freeserf/freeserf/pull/485

**Comment by tlongstretch** [comment]
I merged all the AI code into one new branch and submitted a merge
request for the branch.  I haven't quite figured out git squash yet.

**Pull request closed without merging**
