### PR TITLE
Changed: cpp linting with cmake

### PR DESCRIPTION
**Pull request by wdigger**

### CODE REVIEW

**Comment by jonls** [comment]
👍  So `make check_style` should automatically download and run the style checking script now?

**Comment by wdigger** [comment]
@jonls script downloads on configure step. `check_style` it's an optional target witch run cpplint.

**Comment by jonls** [comment]
@wdigger Is this only supported when using Makefiles with CMake? I've tried to use Ninja as the CMake backend but it doesn't seem to create a `check_style` target.

**Comment by wdigger** [comment]
@jonls I try this with makefile, Xcode and Visual Studio. I never used Ninja.

**Comment by jonls** [comment]
Ok, maybe Ninja support in CMake is not complete yet.

**Comment by wdigger** [comment]
@jonls I tried Ninja and have the same problem.
In any case it's better than nothing.
May be merge this and create new issue for Ninja?

**Comment by jonls** [comment]
@wdigger 👍  Yes, I agree.

**Pull request merged**
