### PR TITLE
Switch CI to GitHub workflows

### PR DESCRIPTION
**Pull request by wdigger**
Switch CI to GitHub workflows

### CODE REVIEW

**Comment by wdigger** [comment]
@jonls can you please disable AppVeyor and travis checks to unlock work on this project?

**Comment by jonls** [comment]
@wdigger Done. Let me know if this works.

**Comment by wdigger** [comment]
@jonls looks like GitHub still using AppVeyor for checking instead of internal workflows. It's possible that AppVeyor integration (webhook?) must be removed at all for propeer work.

**Comment by jonls** [comment]
@wdigger I have deactivated the appveyor and travis webhooks.

**Pull request merged**
