### PR TITLE
Fixed: Issue #170 Building with Visual Studio 2012 & 2013 fails.

### PR DESCRIPTION
**Pull request by wdigger**
"There are missing includes in audio-sdlmixer.c and gfx.c."
Maybe it's about SDL*.h?
SDL only requirement and paths for it must be configured in Visual Studio.

### CODE REVIEW

**Comment by nramsbottom** [comment]
Everything is fixed (assuming SDL is setup correctly), but it still generates errors because of missing includes in gfx.c and audio-sdlmixer.c. Including string.h in both files fixes this.

```
1>------ Build started: Project: freeserf, Configuration: Debug Win32 ------
1>  viewport.c
1>  version.c
1>  serf.c
1>  sdl-video.c
1>  savegame.c
1>  random.c
1>  pqueue.c
1>  popup.c
1>  player.c
1>  pathfinder.cc
1>  panel.c
1>  notification.c
1>  mission.c
1>  minimap.c
1>  map.c
1>  log.c
1>  list.c
1>  interface.c
1>  gui.c
1>  gfx.c
1>d:\dev\projects\freeserf-wdigger-fixes\src\gfx.c(101): error C3861: 'memcmp': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\gfx.c(112): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\gfx.c(259): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\gfx.c(302): error C3861: 'memcpy': identifier not found
1>  Generating Code...
1>  Compiling...
1>  game.c
1>  game-init.c
1>  freeserf.cc
1>  flag.c
1>  data-source-dos.c
1>  building.c
1>  audio-sdlmixer.c
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(154): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(155): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(156): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(159): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(160): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(161): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(162): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(163): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(164): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(165): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(166): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(169): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(170): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(174): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(488): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(528): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(529): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(530): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(531): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(532): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(535): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(537): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(555): error C3861: 'memcpy': identifier not found
1>d:\dev\projects\freeserf-wdigger-fixes\src\audio-sdlmixer.c(566): error C3861: 'memcpy': identifier not found
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by wdigger** [comment]
Although I could import project to VS13 and successfully build it, but including of <string.h> will be useful.
Please, test last commit.

**Comment by wdigger** [comment]
What I have to do for commit was accepted to the master stream?

**Comment by wdigger** [comment]
Rebased to master

**Pull request closed without merging**
