### PR TITLE
Add automatic test of map generator

### PR DESCRIPTION
**Pull request by jonls**
Adds an automatic test that runs the mission map generator for mission 1 and compares the generated data with a memory dump from the original game. This is expected to fail until #236 is merged.

### CODE REVIEW

**Comment by wdigger** [comment]
Is it possible to extract code style check to separated check? Do this check before building steps, and hold build if it failed.

**Comment by jonls** [comment]
@wdigger Do you mean something like running cpplint as a separate build job? On Travis, running the Linux build, OSX build and cpplint in parallel?

**Comment by wdigger** [comment]
Yes, but conditionally - if style check ok, then run all build steps (travis and appveyor).

**Comment by jonls** [comment]
@wdigger I don't know if that's possible. At least I don't know of any way to set it up like that.

**Pull request merged**
