### PR TITLE
Port event loop to c++

### PR DESCRIPTION
**Pull request by wdigger**
Work on porting to C++
I see the following sequence of porting (due that the С code can't use C++ code) -
1. Application and event loop (partially done)
2. GUI
3. Graphics/Video
4. Audio
5. Data loading
6. Game engine

### CODE REVIEW

**Comment by jonls** [comment]
Looks good :+1: It seems like you have a good plan. I merged the two first commits (#177) and I'll take a look at the last commit soon.

**Comment by zdechlak** [comment]
Download PC version in exe files?

2015-09-09 1:13 GMT+02:00 Jon Lund Steffensen <notifications@github.com>:

**Comment by wdigger** [comment]
https://ci.appveyor.com/project/jonls/freeserf/build/12/job/526l5g0usrhtnkbx/artifacts

**Comment by zdechlak** [comment]
What happens to the resolution?


​

2015-10-25 9:51 GMT+01:00 wdigger <notifications@github.com>:

**Comment by zdechlak** [comment]
http://imgur.com/KQYxp48 < print screen

2015-10-26 10:58 GMT+01:00 Bartłomiej Godziński <b.godzinski@gmail.com>:

**Comment by wdigger** [comment]
What's the problem with resolution?

**Comment by zdechlak** [comment]
long time not playing , I forgot how the game looks

Settlers remake needs to zoom :)

**Comment by wdigger** [comment]
New pull request for porting is created.

**Pull request closed without merging**
