### PR TITLE
fix xmi2mid slow convert (game load is about 10 times faster now)

### PR DESCRIPTION
**Pull request by tomsoftware**

### CODE REVIEW

**Comment by wdigger** [comment]
Good work!
Please, merge commits in to one ( https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ ).

**Comment by tomsoftware** [comment]
This is not possible cause it is not posible to update a Pull Request after rebasing it. Or do you want me to delete my pull requests and create new ones?

**Comment by wdigger** [comment]
It's possible of cause. Just merge commits and push it forced.
git rebase -i HEAD~2
... edit for squash ...
... continue rebase ...
git push -f
As result - you change pull request "in place".

**Comment by tomsoftware** [comment]
ok... you are right: I missed the force flag. Thx for helping :-)

**Pull request merged**
